// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Schema = require("../schema/Schema.bs.js");
var Client = require("@prisma/client");

var prisma = new Client.PrismaClient();

var prismaContext = {
  prisma: prisma
};

var nexusSchema = Schema.schema;

exports.prisma = prisma;
exports.prismaContext = prismaContext;
exports.nexusSchema = nexusSchema;
/* prisma Not a pure module */
