// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var GraphqlYoga = require("graphql-yoga");

function server(prim) {
  return new GraphqlYoga.GraphQLServer(prim);
}

exports.server = server;
/* graphql-yoga Not a pure module */
