// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var GraphQLArg = require("./context/GraphQLArg.bs.js");
var GraphqlYoga = require("graphql-yoga");

var config = {
  schema: GraphQLArg.nexusSchema,
  context: GraphQLArg.prismaContext
};

var server = new GraphqlYoga.GraphQLServer(config);

server.start();

exports.config = config;
exports.server = server;
/* server Not a pure module */
