// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Schema = require("@nexus/schema");
var Schema$1 = require("nexus-plugin-prisma/schema'");

var schema = Schema.makeSchema({
      types: [],
      plugins: [Schema$1.nexusSchemaPlugin()],
      outputs: {
        schema: __dirname + "/../schema.graphql"
      }
    });

exports.schema = schema;
/* schema Not a pure module */
